#!/usr/bin/env bash
cd "$(dirname "$0")/../.."
have() { command -v "$1" >/dev/null 2>&1; }
if [[ "$TRAVIS" == "true" ]]; then
  if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
    echo "This is a pull request. No deployment will be done."
    exit 0
  fi
  mvn clean deploy --settings $HOME/.m2/mySettings.xml
fi
